export const projects = [
    {
        id: 1,
        title: "Ideayaan Studio",
        repo: "ideayaan-stack/studio",
        tags: ["React", "Three.js", "Vite"],
        description: "Immersive 3D Hackathon Platform",
        image: "project_ideayaan_abstract.png",
        color: "from-blue-500/10 to-purple-500/10",
        size: "featured",
    },
    {
        id: 2,
        title: "Orbital Flow",
        repo: "Sarvesh2005-code/Orbital-Flow",
        tags: ["Next.js", "React Flow", "Tailwind"],
        description: "Productivity Workflow Automation",
        image: "project_orbital_abstract.png",
        color: "from-emerald-500/10 to-cyan-500/10",
        size: "col-span-1 md:col-span-1 row-span-1",
    },
    {
        id: 3,
        title: "Synk",
        repo: "Sarvesh2005-code/Synk",
        tags: ["TypeScript", "WebSockets", "Node.js"],
        description: "Real-time Synchronization Engine",
        image: "project_synk_abstract.png",
        color: "from-orange-500/10 to-red-500/10",
        size: "col-span-1 md:col-span-1 row-span-2",
    },
    {
        id: 4,
        title: "ITMS Dashboard",
        repo: "Sarvesh2005-code/itms-dashboard",
        tags: ["Next.js", "Tremor", "PostgreSQL"],
        description: "Enterprise Management System",
        image: "project_itms_abstract.png",
        color: "from-zinc-800 to-zinc-900",
        size: "col-span-1 md:col-span-2 row-span-1",
    },
    {
        id: 5,
        title: "DevLinks",
        repo: "Sarvesh2005-code/devlinks",
        tags: ["Next.js", "Firebase", "Tailwind"],
        description: "Developer Portfolio Link Sharing",
        image: "",
        color: "from-purple-600 to-indigo-600",
        size: "col-span-1 md:col-span-1 row-span-1",
    },
    {
        id: 6,
        title: "Eatos",
        repo: "Sarvesh2005-code/Eatos",
        tags: ["React Native", "Expo", "Supabase"],
        description: "Food Delivery App",
        image: "",
        color: "from-yellow-400 to-orange-500",
        size: "col-span-1 md:col-span-2 row-span-1",
    },
];
