export const projects = [
    {
        id: 1,
        title: "Ideayaan Studio",
        description: "Immersive 3D-inspired hackathon platform.",
        tags: ["React", "Three.js", "Vite"],
        link: "https://github.com/ideayaan-stack/studio",
        github: "https://github.com/ideayaan-stack/studio",
        color: "from-blue-500/10 to-purple-500/10",
        size: "col-span-1 md:col-span-2 row-span-2",
    },
    {
        id: 2,
        title: "Orbital Flow",
        description: "A complex workflow automation tool.",
        tags: ["Next.js", "React Flow", "Tailwind"],
        link: "https://github.com/Sarvesh2005-code/Orbital-Flow",
        github: "https://github.com/Sarvesh2005-code/Orbital-Flow",
        color: "from-emerald-500/10 to-cyan-500/10",
        size: "col-span-1 md:col-span-1 row-span-1",
    },
    {
        id: 3,
        title: "Synk",
        description: "Real-time synchronization engine.",
        tags: ["TypeScript", "WebSockets", "Node.js"],
        link: "https://github.com/Sarvesh2005-code/Synk",
        github: "https://github.com/Sarvesh2005-code/Synk",
        color: "from-orange-500/10 to-red-500/10",
        size: "col-span-1 md:col-span-1 row-span-2",
    },
    {
        id: 4,
        title: "ITMS Dashboard",
        description: "Comprehensive management dashboard for IT systems.",
        tags: ["Next.js", "Tremor", "PostgreSQL"],
        link: "https://github.com/Sarvesh2005-code/itms-dashboard",
        github: "https://github.com/Sarvesh2005-code/itms-dashboard",
        color: "from-zinc-800 to-zinc-900",
        size: "col-span-1 md:col-span-2 row-span-1",
    },
];
