export const projects = [
    {
        id: 1,
        title: "Ideayaan Studio",
        repo: "ideayaan-stack/studio",
        tags: ["React", "Three.js", "Vite"],
        image: "project_ideayaan_abstract.png",
        color: "from-blue-500/10 to-purple-500/10",
        size: "col-span-1 md:col-span-2 row-span-2",
    },
    {
        id: 2,
        title: "Orbital Flow",
        repo: "Sarvesh2005-code/Orbital-Flow",
        tags: ["Next.js", "React Flow", "Tailwind"],
        image: "project_orbital_abstract.png",
        color: "from-emerald-500/10 to-cyan-500/10",
        size: "col-span-1 md:col-span-1 row-span-1",
    },
    {
        id: 3,
        title: "Synk",
        repo: "Sarvesh2005-code/Synk",
        tags: ["TypeScript", "WebSockets", "Node.js"],
        image: "project_synk_abstract.png",
        color: "from-orange-500/10 to-red-500/10",
        size: "col-span-1 md:col-span-1 row-span-2",
    },
    {
        id: 4,
        title: "ITMS Dashboard",
        repo: "Sarvesh2005-code/itms-dashboard",
        tags: ["Next.js", "Tremor", "PostgreSQL"],
        image: "project_itms_abstract.png",
        color: "from-zinc-800 to-zinc-900",
        size: "col-span-1 md:col-span-2 row-span-1",
    },
];
